In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split


In [3]:
from keras.models import Sequential
from keras.layers import Dense,Activation

In [5]:
data = pd.read_csv('tic-tac-toe.csv')

In [7]:
X = data.iloc[:,0:9].values
Y = data.iloc[:,9:10].values

In [14]:
#Encode categorical values
labelencoder_x = LabelEncoder()
for i in range(9):
    X[:,i] = labelencoder_x.fit_transform(X[:,i])


In [12]:

onehotencoder = OneHotEncoder(categorical_features=[0,1,2,3,4,5,6,7,8])
X = onehotencoder.fit_transform(X).toarray()
print(X[0:4,:])

[[1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0.
  1. 1. 0.]
 [1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.
  0. 0. 1.]
 [1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0.
  0. 0. 0.]
 [1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1.
  0. 0. 0.]]


In [15]:
#only 2 bits are required to represent 3 possibilties...remove 3's multiple column 
X = np.delete(X,[0,3,6,9,12,15,18,21,24],axis =1)
print(X[0:4,:])

[[0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0.]]


In [16]:
labelencoder_y =LabelEncoder()
Y[:, 0] = labelencoder_y.fit_transform(y[:, 0])

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [19]:
model = Sequential()
model.add(Dense(9,input_dim = 18,activation = 'relu'))
model.add(Dense(9,activation='relu'))
model.add(Dense(1,activation = 'sigmoid'))

In [20]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [21]:
model.fit(X,Y,batch_size=10, epochs=100)

Epoch 1/100
957/957 [==============================] - 1s 1ms/step - loss: 0.6548 - acc: 0.6416
Epoch 2/100
957/957 [==============================] - 0s 225us/step - loss: 0.6047 - acc: 0.7095
Epoch 3/100
957/957 [==============================] - 0s 227us/step - loss: 0.5733 - acc: 0.7085
Epoch 4/100
957/957 [==============================] - 0s 213us/step - loss: 0.5371 - acc: 0.7398
Epoch 5/100
957/957 [==============================] - 0s 219us/step - loss: 0.5123 - acc: 0.7388
Epoch 6/100
957/957 [==============================] - 0s 234us/step - loss: 0.4915 - acc: 0.7618
Epoch 7/100
957/957 [==============================] - 0s 217us/step - loss: 0.4732 - acc: 0.7649
Epoch 8/100
957/957 [==============================] - 0s 229us/step - loss: 0.4586 - acc: 0.7879
Epoch 9/100
957/957 [==============================] - 0s 238us/step - loss: 0.4410 - acc: 0.8025
Epoch 10/100
957/957 [==============================] - 0s 242us/step - loss: 0.4247 - acc: 0.8067
Epoch 11/100
957/957 

957/957 [==============================] - 0s 227us/step - loss: 0.1071 - acc: 0.9592
Epoch 84/100
957/957 [==============================] - 0s 230us/step - loss: 0.1082 - acc: 0.9634
Epoch 85/100
957/957 [==============================] - 0s 219us/step - loss: 0.1060 - acc: 0.9676
Epoch 86/100
957/957 [==============================] - 0s 218us/step - loss: 0.1040 - acc: 0.9697
Epoch 87/100
957/957 [==============================] - 0s 232us/step - loss: 0.1042 - acc: 0.9676
Epoch 88/100
957/957 [==============================] - 0s 241us/step - loss: 0.1019 - acc: 0.9645
Epoch 89/100
957/957 [==============================] - 0s 246us/step - loss: 0.0989 - acc: 0.9697
Epoch 90/100
957/957 [==============================] - 0s 211us/step - loss: 0.0983 - acc: 0.9707
Epoch 91/100
957/957 [==============================] - 0s 230us/step - loss: 0.0948 - acc: 0.9718
Epoch 92/100
957/957 [==============================] - 0s 215us/step - loss: 0.0965 - acc: 0.9676
Epoch 93/100
957/957 [=

In [23]:
scores = model.evaluate(X,Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

957/957 [==============================] - 0s 78us/step

acc: 97.70%


In [24]:
y_pred = model.predict(X_test)